### ISSUE TITLE
Cookbook fails for windows

### ISSUE THREAD

**Issue by shgattu** [tkuhlman/cookbooks-vertica#3]
Hi,
I see a weird issue when I use this cookbook. Chef recipe cannot enable verticad. Below is the stacktrace
 default: [2015-04-29T22:36:27+00:00] INFO: template[/etc/security/limits.d/vertica.conf] created file /etc/security/limits.d/vertica.conf
 default: [2015-04-29T22:36:27+00:00] INFO: template[/etc/security/limits.d/vertica.conf] updated file contents /etc/security/limits.d/vertica.conf
 default: [2015-04-29T22:36:27+00:00] INFO: template[/etc/security/limits.d/vertica.conf] owner changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: template[/etc/security/limits.d/vertica.conf] group changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: template[/etc/security/limits.d/vertica.conf] mode changed to 644
 default: [2015-04-29T22:36:27+00:00] INFO: bash[su_pam_limits] ran successfully
 default: [2015-04-29T22:36:27+00:00] INFO: file[/etc/profile.d/vertica_node.sh] created file /etc/profile.d/vertica_node.sh
 default: [2015-04-29T22:36:27+00:00] INFO: file[/etc/profile.d/vertica_node.sh] updated file contents /etc/profile.d/vertica_node.sh
 default: [2015-04-29T22:36:27+00:00] INFO: file[/etc/profile.d/vertica_node.sh] owner changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: file[/etc/profile.d/vertica_node.sh] group changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: file[/etc/profile.d/vertica_node.sh] mode changed to 644
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica] created directory /var/vertica
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica] owner changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica] group changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica] mode changed to 755
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica/downloads] created directory /var/vertica/downloads
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica/downloads] owner changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica/downloads] group changed to 0
 default: [2015-04-29T22:36:27+00:00] INFO: directory[/var/vertica/downloads] mode changed to 755
 default: [2015-04-29T22:38:59+00:00] INFO: remote_file[/var/vertica/downloads/vertica_7.1.1-0_amd64.deb] created file /var/vertica/downloads/vertica_7.1.1-0_amd64.deb
 default: [2015-04-29T22:38:59+00:00] INFO: remote_file[/var/vertica/downloads/vertica_7.1.1-0_amd64.deb] updated file contents /var/vertica/downloads/vertica_7.1.1-0_amd64.deb
 default: [2015-04-29T22:40:26+00:00] INFO: remote_file[/var/vertica/downloads/vertica-r-lang_7.1.1-0_amd64.deb] created file /var/vertica/downloads/vertica-r-lang_7.1.1-0_amd64.deb
 default: [2015-04-29T22:40:26+00:00] INFO: remote_file[/var/vertica/downloads/vertica-r-lang_7.1.1-0_amd64.deb] updated file contents /var/vertica/downloads/vertica-r-lang_7.1.1-0_amd64.deb
 default: [2015-04-29T22:43:56+00:00] INFO: remote_file[/var/vertica/downloads/vertica-console_7.1.1-0_amd64.deb] created file /var/vertica/downloads/vertica-console_7.1.1-0_amd64.deb
 default: [2015-04-29T22:43:57+00:00] INFO: remote_file[/var/vertica/downloads/vertica-console_7.1.1-0_amd64.deb] updated file contents /var/vertica/downloads/vertica-console_7.1.1-0_amd64.deb
 default: [2015-04-29T22:44:01+00:00] INFO: remote_file[/var/vertica/downloads/vertica-cURLLib_7.1.1-0_amd64.so] created file /var/vertica/downloads/vertica-cURLLib_7.1.1-0_amd64.so
 default: [2015-04-29T22:44:01+00:00] INFO: remote_file[/var/vertica/downloads/vertica-cURLLib_7.1.1-0_amd64.so] updated file contents /var/vertica/downloads/vertica-cURLLib_7.1.1-0_amd64.so
 default: [2015-04-29T22:44:11+00:00] INFO: remote_file[/var/vertica/downloads/vertica-flextable-custom_7.1.1-0_amd64.so] created file /var/vertica/downloads/vertica-flextable-custom_7.1.1-0_amd64.so
 default: [2015-04-29T22:44:11+00:00] INFO: remote_file[/var/vertica/downloads/vertica-flextable-custom_7.1.1-0_amd64.so] updated file contents /var/vertica/downloads/vertica-flextable-custom_7.1.1-0_amd64.so
 default: [2015-04-29T22:44:11+00:00] INFO: ruby_block[download_vertica] called
 default: [2015-04-29T22:44:11+00:00] INFO: dpkg_package[vertica] installing /var/vertica/downloads/vertica_7.1.1-0_amd64.deb
 default: [2015-04-29T22:44:15+00:00] INFO: dpkg_package[vertica] installed vertica at 7.1.1-0
 default: [2015-04-29T22:44:15+00:00] INFO: dpkg_package[vertica-R-lang] installing /var/vertica/downloads/vertica-r-lang_7.1.1-0_amd64.deb
 default: [2015-04-29T22:44:16+00:00] INFO: dpkg_package[vertica-R-lang] installed vertica-R-lang at 7.1.1-0
 default: [2015-04-29T22:44:16+00:00] INFO: user[dbadmin] created
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/home/dbadmin/.ssh] created directory /home/dbadmin/.ssh
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/home/dbadmin/.ssh] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/home/dbadmin/.ssh] group changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/home/dbadmin/.ssh] mode changed to 700
 default: [2015-04-29T22:44:16+00:00] INFO: file[/home/dbadmin/.ssh/config] created file /home/dbadmin/.ssh/config
 default: [2015-04-29T22:44:16+00:00] INFO: file[/home/dbadmin/.ssh/config] updated file contents /home/dbadmin/.ssh/config
 default: [2015-04-29T22:44:16+00:00] INFO: file[/home/dbadmin/.ssh/config] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: file[/home/dbadmin/.ssh/config] group changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: file[/home/dbadmin/.ssh/config] mode changed to 600
 default: [2015-04-29T22:44:16+00:00] INFO: bash[create ssh key] ran successfully
 default: [2015-04-29T22:44:16+00:00] INFO: group[verticadba] created
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/users/dbadmin] created directory /opt/vertica/config/users/dbadmin
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/users/dbadmin] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/users/dbadmin] group changed to 0
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/users/dbadmin] mode changed to 775
 default: [2015-04-29T22:44:16+00:00] INFO: file[/opt/vertica/config/users/dbadmin/agent.conf] created file /opt/vertica/config/users/dbadmin/agent.conf
 default: [2015-04-29T22:44:16+00:00] INFO: file[/opt/vertica/config/users/dbadmin/agent.conf] owner changed to 0
 default: [2015-04-29T22:44:16+00:00] INFO: file[/opt/vertica/config/users/dbadmin/agent.conf] group changed to 0
 default: [2015-04-29T22:44:16+00:00] INFO: file[/opt/vertica/config/users/dbadmin/agent.conf] mode changed to 664
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/data] created directory /mnt/vertica/data
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/data] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/data] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/data] mode changed to 770
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/catalog] created directory /mnt/vertica/catalog
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/catalog] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/catalog] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/mnt/vertica/catalog] mode changed to 770
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config] mode changed to 775
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/share] created directory /opt/vertica/config/share
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/share] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/share] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/config/share] mode changed to 775
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/log] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/log] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: directory[/opt/vertica/log] mode changed to 775
 default: [2015-04-29T22:44:16+00:00] INFO: link[/etc/init.d/vertica_agent] created
 default: [2015-04-29T22:44:16+00:00] INFO: link[/etc/init.d/verticad] created
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat] created file /opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat] updated file contents /opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/d5415f948449e9d4c421b568f2411140.dat] mode changed to 775
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/license.key] created file /opt/vertica/config/share/license.key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/license.key] updated file contents /opt/vertica/config/share/license.key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/license.key] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/license.key] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/license.key] mode changed to 644
 default: [2015-04-29T22:44:16+00:00] WARN: Using insecure default agent ssl certificate and key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.key] created file /opt/vertica/config/share/agent.key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.key] updated file contents /opt/vertica/config/share/agent.key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.key] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.key] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.key] mode changed to 400
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.cert] created file /opt/vertica/config/share/agent.cert
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.cert] updated file contents /opt/vertica/config/share/agent.cert
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.cert] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.cert] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.cert] mode changed to 400
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.pem] created file /opt/vertica/config/share/agent.pem
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.pem] updated file contents /opt/vertica/config/share/agent.pem
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.pem] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.pem] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/opt/vertica/config/share/agent.pem] mode changed to 400
 default: [2015-04-29T22:44:16+00:00] WARN: Using insecure default database ssl certificate and key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.key] created file /mnt/vertica/catalog/../server.key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.key] updated file contents /mnt/vertica/catalog/../server.key
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.key] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.key] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.key] mode changed to 400
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.crt] created file /mnt/vertica/catalog/../server.crt
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.crt] updated file contents /mnt/vertica/catalog/../server.crt
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.crt] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.crt] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: cookbook_file[/mnt/vertica/catalog/../server.crt] mode changed to 444
 default: [2015-04-29T22:44:16+00:00] INFO: template[/opt/vertica/config/admintools.conf] created file /opt/vertica/config/admintools.conf
 default: [2015-04-29T22:44:16+00:00] INFO: template[/opt/vertica/config/admintools.conf] updated file contents /opt/vertica/config/admintools.conf
 default: [2015-04-29T22:44:16+00:00] INFO: template[/opt/vertica/config/admintools.conf] owner changed to 1002
 default: [2015-04-29T22:44:16+00:00] INFO: template[/opt/vertica/config/admintools.conf] group changed to 1003
 default: [2015-04-29T22:44:16+00:00] INFO: template[/opt/vertica/config/admintools.conf] mode changed to 660
 default: [2015-04-29T22:44:16+00:00] INFO: service[vertica_agent] enabled
 default: [2015-04-29T22:44:16+00:00] INFO: service[vertica_agent] started
 default: ================================================================================
 default: Error executing action `enable` on resource 'service[verticad]'
 default: ================================================================================
 default:
 default: Mixlib::ShellOut::CommandTimeout
 default: --------------------------------
 default: Command timed out after 600s:
 default: Command exceeded allowed execution time, process terminated
 default: ---- Begin output of /etc/init.d/verticad status ----
 default: STDOUT: Vertica:
 default: STDERR: Session terminated, terminating shell... ...terminated.
 default: ---- End output of /etc/init.d/verticad status ----
 default: Ran /etc/init.d/verticad status returned
 default:
 default: Resource Declaration:
 default: ---------------------
 default: # In /tmp/vagrant-chef/52b8481e0edc95feca30ca3915ab32f3/cookbooks/vertica/recipes/default.rb
 default:
 default:  65: service 'verticad' do
 default:  66:   action :enable
 default:  67:   supports :status => true, :restart => true
 ==> default:  68: end
==> default:  69:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/52b8481e0edc95feca30ca3915ab32f3/cookbooks/vertica/recipes/default.rb:65:in `from_file'
==> default:
==> default: service("verticad") do
==> default:   action [:enable]
==> default:   supports {:status=>true, :restart=>true}
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   service_name "verticad"
==> default:   pattern "verticad"
==> default:   declared_type :service
==> default:   cookbook_name :vertica
==> default:   recipe_name "default"
==> default: end
==> default: [2015-04-29T22:54:41+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-04-29T22:54:41+00:00] ERROR: Running exception handlers
==> default: [2015-04-29T22:54:41+00:00] ERROR: Exception handlers complete
==> default: [2015-04-29T22:54:41+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-04-29T22:54:41+00:00] ERROR: service[verticad](vertica::default line 65) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
==> default: Command exceeded allowed execution time, process terminated
==> default: ---- Begin output of /etc/init.d/verticad status ----
==> default: STDOUT: Vertica:
==> default: STDERR: Session terminated, terminating shell... ...terminated.
==> default: ---- End output of /etc/init.d/verticad status ----
==> default: Ran /etc/init.d/verticad status returned
==> default: [2015-04-29T22:54:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the

**Comment by shgattu** [comment]
Vagrant version is 1.7.2

**Comment by shgattu** [comment]
More information on this:
When I run ./verticad status the response I get is 
EULA not accepted

**Comment by tkuhlman** [comment]
On windows? I hope you mean you vagrant host is windows not anything to do with the vertica install.

I haven't run this cookbook with 7.1, try Vertica 7.0.1 and see if it works for you. It is possible something changed and the cookbook needs updating for 7.1.

**Comment by shgattu** [comment]
I was running on Vertica 7.0.1. It was not the issue with your script but my git config
I was seeing EULA agreement issue because I didn’t set up my git config properly with autocrlf=false.
License file was not matching.

**Comment by shgattu** [comment]
Issue is resolved
